spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localspringbootdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true

    properties:
      hibernate:
      format_sql: true